# Generated by Django 5.1.3 on 2024-11-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrower',
            name='ivr_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrower',
            name='message_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrower',
            name='payment_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrower',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='whatsapp_sent',
            field=models.BooleanField(default=False),
        ),
    ]
