# Generated by Django 5.1.3 on 2024-11-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_borrower_email_sent_borrower_ivr_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='notification_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
